import logging

ENDERECO_SERVIDOR = '127.0.0.1'
PORTO = 8000
COMMAND_SIZE = 11
X_MAX = "max x      "
Y_MAX = "max y      "
GRID = "grid       "
HIT = "hit        "
SHOT = "shot       "
MSG_SIZE = 40
N_BYTES = 8
ACCEPT_TIMEOUT = 1
CODIFICACAO_STR = 'utf-8'
SUNKEN = "sunken     "
NOME_FICHEIRO_LOG = "game-server.log"
NIVEL_LOG = logging.DEBUG
GET_HIT = "get hit    "
GET_SHOT = "get shot   "
MISS = "miss       "
NR_CLIENTS = 2
ADD_PLAYER = "add player "
START_GAME = "start game "
TRUE = "True"
GET_PLAYERS = "get players"
NR_PLAYERS = "nr players "
TURN_END = "turn ended "
UPDATE = "update     "
END_GAME = "end game   "
